#ifndef TUDOUALGORITHM_GLOBAL_H
#define TUDOUALGORITHM_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TUDOUALGORITHM_LIBRARY)
#  define TUDOUALGORITHM_EXPORT Q_DECL_EXPORT
#else
#  define TUDOUALGORITHM_EXPORT Q_DECL_IMPORT
#endif

#endif // TUDOUALGORITHM_GLOBAL_H
